export const OSMap = new Map([
  ['windows 98', '98'],
  ['windows 95', '95'],
  ['windows nt 4.', 'NT'],
  ['windows nt 5.0', '2000'],
  ['windows nt 5.1', 'XP'],
  ['windows nt 5.2', '2003'],
  ['windows nt 6.0', 'Vista'],
  ['windows 9x', 'ME'],
  ['windows ce', 'CE'],
  ['windows', 'Windows'],
  ['mac', 'MAC'],
  ['linux', 'Linux'],
  ['irix', 'IRIX'],
  ['phone', 'Phone'],
  ['bot', 'Robot'],
  ['slurp', 'Robot'],
  ['internet explorer', 'IE'],
  ['mozilla', 'Mozilla'],
]);

export const BrowserMap = new Map([
  ['msie 5.0', 'MSIE 5.0'],
  ['msie 5.5', 'MSIE 5.5'],
  ['msie 6.0', 'MSIE 6.0'],
  ['msie 7.0', 'MSIE 7.0'],
  ['msie 8.0', 'MSIE 8.0'],
  ['msie 4.0', 'MSIE 4.x'],
  ['firefox', 'FireFox'],
  ['chrome', 'Chrome'],
  ['x11', 'Netscape'],
  ['opera', 'Opera'],
  ['gec', 'Gecko'],
  ['bot', 'Robot'],
  ['slurp', 'Robot'],
  ['internet explorer', 'IE'],
  ['mozilla', 'Mozilla'],
]);

export const TimeMaxLength = {
  hour: 24,
  date: 7,
  day: 31,
  month: 12,
  year: 0,
};
