export const CouponItemsInit = [
  {
    name: '배당률 5% 증가 아이템',
    rate: 5,
    price: 10000,
    description: '적용 게임 배당율이 증가합니다. 2.00 ↑ 5% = 2.1',
    itemIndex: 1,
    unit: 'coin',
  },
  {
    name: '배당률 10% 증가 아이템',
    rate: 10,
    price: 20000,
    itemIndex: 2,
    description: '적용 게임 배당율이 증가합니다. 2.00 ↑ 10% = 2.2',
    unit: 'coin',
  },
  {
    name: '배당률 15% 증가 아이템',
    rate: 15,
    price: 30000,
    itemIndex: 3,
    description: '적용 게임 배당율이 증가합니다. 2.00 ↑ 15% = 2.3',
    unit: 'coin',
  },
  {
    name: '20% 미적중 환급 아이템',
    rate: 20,
    price: 40000,
    itemIndex: 4,
    description: '미적중시 배팅금액의 20% 를 돌려드립니다.',
    unit: 'coin',
  },
  {
    name: '35% 미적중 환급 아이템',
    rate: 35,
    price: 70000,
    itemIndex: 5,
    description: '미적중시 배팅금액의 35% 를 돌려드립니다.',
    unit: 'coin',
  },
  {
    name: '50% 미적중 환급 아이템',
    rate: 50,
    price: 100000,
    itemIndex: 6,
    description: '미적중시 배팅금액의 50% 를 돌려드립니다.',
    unit: 'coin',
  },
  {
    name: '적중특례 아이템',
    rate: 100,
    price: 50000,
    itemIndex: 7,
    description: '미적중 경기를 적중특례 시킵니다',
    unit: 'coin',
  },
];
