export const TopLeaguesInit = [
  {
    name: 'Top 5',
    nameKo: '유럽 5대리그',
    order: 1,
    imageUrl: null,
    description: null,
    leagues: ['Premier League', 'Bundesliga', 'LaLiga', 'Serie A', 'Ligue 1'],
  },
  {
    name: 'Japan',
    nameKo: '일본주요리그',
    order: 2,
    imageUrl: null,
    description: null,
    leagues: [
      'J1 League',
      'J2 League',
      'J3 League',
      'Japan Football League',
      'Japanese Regional Leagues',
    ],
  },
  {
    name: 'South Korea',
    nameKo: '대한민국리그',
    order: 3,
    imageUrl: null,
    description: null,
    leagues: [
      'K League 1',
      'K League 2',
      'K3 League',
      'K4 League',
      'K5 League',
    ],
  },
  {
    name: 'USA',
    nameKo: '미국주요리그',
    order: 4,
    imageUrl: null,
    description: null,
    leagues: ['NFL', 'NBA', 'MLS', 'MLB', 'NHL'],
  },
  {
    name: 'World division 1',
    nameKo: '세계1부리그',
    order: 5,
    imageUrl: null,
    description: null,
    leagues: [],
  },
  {
    name: 'Pro League',
    nameKo: '프로토리그',
    order: 6,
    imageUrl: null,
    description: null,
    leagues: [],
  },
];
