name: Detect File Changes Workflow

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/**'
  pull_request:
    paths:
      - 'apps/**'
      - 'gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Auth Service
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified | contains('apps/auth-service') }}
        run: echo build Auth-service

      - name: Build Auth Service
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified | contains('apps/auth-service') }}
        run: echo build auth-service

      - name: Build Calculate Service
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified | contains('apps/calculate-service') }}
        run: echo build calculate-service

      # Run build for the admin gateway if changes are detected
      - name: Build Admin Gateway
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified | contains('apps/admin-gateway') }}
        run: echo build admin-gateway

    # Add more steps for other services and gateways if needed
