name: Deploy auth-service

on:
  push:
    branches:
      - develop
    paths:
      - "apps/auth-service/**"
      - "!apps/auth-service/.sample.env"

jobs:
  deploy-auth-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Get short commit hash
        id: commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Login Docker Hub
        uses: docker/login-action@v1
        id: docker_session
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      # Build images:

      - name: Build auth-service
        uses: docker/build-push-action@v2
        id: build-auth-service
        with:
          context: .
          file: ./apps/auth-service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/auth-service:${{ steps.commit_hash.outputs.hash }} , ${{secrets.DOCKER_USERNAME}}/auth-service:latest

      - name: Verify Build auth-service
        run: echo ${{ steps.build-auth-service.outputs.digest }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ../deploy/nest-microservices
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker pull ${{secrets.DOCKER_USERNAME}}/auth-service:latest
            docker-compose -f docker-compose.deploy.yml up -d
            docker image prune -f

