name: CI

on:
  push:
    branches:
      - master

jobs:
  setup_docker:
    runs-on: ubuntu-latest
      outputs:
        buildx: ${{ steps.buildx.outputs.name }}

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        id: docker_session
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

  check_change_files:
    runs-on: ubuntu-latest
    outputs:
      auth: ${{ steps.auth.outputs.state }}
      config: ${{ steps.config.outputs.state }}
      calculate: ${{ steps.calculate.outputs.state }}
      member: ${{ steps.member.outputs.state }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: Check Auth Service
        id: auth
        if: contains(steps.changed-files.outputs.modified_files, 'apps/auth-service')
        run: echo "state=true" >> $GITHUB_OUTPUT

      - name: Check Config Service
        id: config
        if: contains(steps.changed-files.outputs.modified_files, 'apps/config-service')
        run: echo "state=true" >> $GITHUB_OUTPUT

      - name: Check Member Service
        id: member
        if: contains(steps.changed-files.outputs.modified_files, 'apps/member-service')
        run: echo "state=true" >> $GITHUB_OUTPUT

      - name: Check Calculate Service
        id: calculate
        if: contains(steps.changed-files.outputs.modified_files, 'apps/calculate-service')
        run: echo "state=true" >> $GITHUB_OUTPUT

      - name: Display
        run: |
          echo "Is auth change: ${{ steps.auth.outputs.state }}"
          echo "Is config change: ${{ steps.config.outputs.state }}"
          echo "Is calculate change: ${{ steps.calculate.outputs.state }}"
          echo "Is member change: ${{ steps.member.outputs.state }}"

  deploy_auth:
    needs: [check_change_files, setup_docker]
    if: ${{ needs.check_change_files.outputs.auth == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Auth service
        uses: docker/build-push-action@v2
        id: build-auth-service
        with:
          context: .
          file: ./apps/auth-service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/auth-service:latest

  deploy_member:
    needs: [check_change_files, setup_docker]
    if: ${{ needs.check_change_files.outputs.member == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Member service
        uses: docker/build-push-action@v2
        id: build-member-service
        with:
          context: .
          file: ./apps/member-service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/member-service:latest

  deploy_calculate:
    needs: [check_change_files, setup_docker]
    if: ${{ needs.check_change_files.outputs.calculate == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Calculate service
        uses: docker/build-push-action@v2
        id: build-calculate-service
        with:
          context: .
          file: ./apps/calculate-service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/calculate-service:latest

  deploy_config:
    needs: [check_change_files, setup_docker]
    if: ${{ needs.check_change_files.outputs.config == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Config service
        uses: docker/build-push-action@v2
        id: build-config-service
        with:
          context: .
          file: ./apps/config-service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/config-service:latest

  deploy_admin:
    needs:
      [
        check_change_files,
        deploy_config,
        deploy_calculate,
        deploy_member,
        deploy_auth,
        setup_docker
      ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build admin gateway
        uses: docker/build-push-action@v2
        id: build-admin-gateway
        with:
          context: .
          file: ./apps/admin-gateway/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/admin-gateway:latest
