name: Test migration

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
    paths:
      - libs/core/databases/postgres/migrations/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Print current branch
        run: echo "$(git branch)"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v1
        id: docker_session
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build migrate-image
        uses: docker/build-push-action@v2
        id: build-migrate-image
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/migrate-image:latest

      - name: Verify Build migrate-image
        run: echo ${{ steps.build-migrate-image.outputs.digest }}

      - name: Run migration on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ../deploy/nest-microservices
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker pull ${{secrets.DOCKER_USERNAME}}/migrate-image:latest
            docker run --env-file ./.env --net=host --name migrate-image ${{secrets.DOCKER_USERNAME}}/migrate-image
            docker rm migrate-image
            docker image prune -a -f

